apiVersion: v1
kind: Service
metadata:
  name: "nginx-svc-{{ .Values.env }}"
  labels:
    app: helmSample
spec:
  selector:
    app: helmSample
  type: {{ .Values.service.type | quote }}
  {{- if eq "ClusterIP" .Values.service.type }}
  clusterIP: None
  {{- end }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
      {{- if eq "NodePort" .Values.service.type }}
      {{- if .Values.service.web.nodePort }}
      nodePort: {{ .Values.service.web.nodePort }}
      {{- end }}
      {{- end }}
