name: Lint workflows
run-name: ${{ github.workflow }} - ${{ github.event.pull_request.title }}

on:
  pull_request_target:
    branches:
      - main
    paths:
      - ".github/workflows/*.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  lint:
    name: Lint workflows
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
